# Generated by Django 5.0.8 on 2024-08-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenantLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField()),
                ('log_file', models.FileField(upload_to='logs/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
